export const USER_NAME_MIN_LENGTH = 2;
export const USER_NAME_MAX_LENGTH = 50;

export const PHARMACY_NAME_MIN_LENGTH = 2;
export const PHARMACY_NAME_MAX_LENGTH = 100;

export const BANK_RECIPIENT_NAME_MIN_LENGTH = 2;
export const BANK_RECIPIENT_NAME_MAX_LENGTH = 160;

export const BANK_NAME_MIN_LENGTH = 2;
export const BANK_NAME_MAX_LENGTH = 120;

export const USER_EMAIL_MAX_LENGTH = 64;
export const USER_PHONE_MAX_LENGTH = 13;

export const USER_PASSWORD_MIN_LENGTH = 8;
export const USER_PASSWORD_MAX_LENGTH = 20;

export const USER_ADDRESS_MIN_LENGTH = 10;
export const USER_ADDRESS_MAX_LENGTH = 200;

export const USER_SEARCH_MAX_LENGTH = 80;

export const USER_REVIEW_COMMENT_MIN_LENGTH = 10;
export const USER_REVIEW_COMMENT_MAX_LENGTH = 500;

export const MIN_REVIEW_RATING = 1;
export const MAX_REVIEW_RATING = 5;

export const USER_ORDER_COMMENT_MAX_LENGTH = 500;

export const WORKING_HOURS_MAX_LENGTH = 160;
export const TEXT_EDITOR_MAX_LENGTH = 5000;

export const TAX_ID_MIN_LENGTH = 8;
export const TAX_ID_MAX_LENGTH = 10;

export const IBAN_MAX_LENGTH = 29;
export const PAYMENT_PURPOSE_MAX_LENGTH = 500;

export const PICTURE_URL_MAX_LENGTH = 700000;
export const PICTURE_FILE_MAX_SIZE_BYTES = 450 * 1024;
