export const PHARMACY_PROFILE_MISSING_ERROR_CODE =
  'PHARMACY_PROFILE_MISSING';

export const PHARMACY_PROFILE_BLOCKED_ERROR_CODE =
  'PHARMACY_PROFILE_BLOCKED';

export const PHARMACY_PROFILE_LOCKED_ERROR_CODE =
  'PHARMACY_PROFILE_LOCKED';

export const PHARMACY_PROFILE_INCOMPLETE_ERROR_CODE =
  'PHARMACY_PROFILE_INCOMPLETE';

export const PHARMACY_NO_PENDING_CHANGES_ERROR_CODE =
  'PHARMACY_NO_PENDING_CHANGES';
