export const PHARMACY_PROFILE_MISSING_ERROR_CODE =
  'PHARMACY_PROFILE_MISSING';

export const PHARMACY_PROFILE_BLOCKED_ERROR_CODE =
  'PHARMACY_PROFILE_BLOCKED';

export const PHARMACY_PROFILE_LOCKED_ERROR_CODE =
  'PHARMACY_PROFILE_LOCKED';

export const PHARMACY_PROFILE_CONFLICT_ERROR_CODE =
  'PHARMACY_PROFILE_CONFLICT';

export const PHARMACY_PROFILE_INCOMPLETE_ERROR_CODE =
  'PHARMACY_PROFILE_INCOMPLETE';

export const PHARMACY_NO_PENDING_CHANGES_ERROR_CODE =
  'PHARMACY_NO_PENDING_CHANGES';

export const PHARMACY_PROFILE_ALREADY_SUBMITTED_ERROR_CODE =
  'PHARMACY_PROFILE_ALREADY_SUBMITTED';

export const PHARMACY_MODERATION_SUBMISSION_REQUIRED_ERROR_CODE =
  'PHARMACY_MODERATION_SUBMISSION_REQUIRED';

export const PHARMACY_OWNER_REQUIRED_ERROR_CODE =
  'PHARMACY_OWNER_REQUIRED';
