export {
  EMAIL_MAX_LENGTH,
  FORGOT_PASSWORD_INITIAL_VALUES,
  LOGIN_INITIAL_VALUES,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  REGISTER_INITIAL_VALUES,
  RESET_PASSWORD_INITIAL_VALUES,
  USER_NAME_MAX_LENGTH,
  USER_NAME_MIN_LENGTH,
  getEmailError,
  getPasswordError,
  sanitizeCustomerPhone,
  sanitizeEmail,
  validateForgotPasswordForm,
  validateLoginForm,
  validateRegisterForm,
  validateResetPasswordForm,
  type ForgotPasswordFormErrors,
  type ForgotPasswordFormValues,
  type LoginFormErrors,
  type LoginFormValues,
  type RegisterFormErrors,
  type RegisterFormValues,
  type ResetPasswordFormErrors,
  type ResetPasswordFormValues,
} from './auth-validation';

export {
  CUSTOMER_ADDRESS_MAX_LENGTH,
  CUSTOMER_ADDRESS_MIN_LENGTH,
  CUSTOMER_ADDRESS_REGEX,
  CUSTOMER_NAME_MAX_LENGTH,
  CUSTOMER_NAME_MIN_LENGTH,
  CUSTOMER_NAME_REGEX,
  CUSTOMER_PHONE_MAX_LENGTH,
  CUSTOMER_PHONE_MIN_LENGTH,
  CUSTOMER_PHONE_REGEX,
  getCustomerAddressError,
  getCustomerNameError,
  getCustomerPhoneError,
  sanitizeCustomerAddress,
  sanitizeCustomerName,
} from './customer-fields';
