export const PRODUCT_REQUEST_ERROR_CODES = {
  ARTICLE_CONFLICT: 'PRODUCT_REQUEST_ARTICLE_CONFLICT',
  NOT_FOUND: 'PRODUCT_REQUEST_NOT_FOUND',
  NOT_EDITABLE: 'PRODUCT_REQUEST_NOT_EDITABLE',
  NOT_DELETABLE: 'PRODUCT_REQUEST_NOT_DELETABLE',
  INVALID_TRANSITION: 'PRODUCT_REQUEST_INVALID_TRANSITION',
  REJECTION_REASON_REQUIRED: 'PRODUCT_REQUEST_REJECTION_REASON_REQUIRED',
  APPROVAL_PRODUCT_CONFLICT: 'PRODUCT_REQUEST_APPROVAL_PRODUCT_CONFLICT',
} as const;
