export const ROUTE_SEGMENTS = {
  pharmacies: 'pharmacies',
  productCatalog: 'product-catalog',
  cart: 'cart',
  checkout: 'checkout',
  login: 'login',
  register: 'register',
  passwordRecovery: 'password-recovery',
  resetPassword: 'reset-password',
  profile: 'profile',
  deliveryPayment: 'delivery-and-payment',
  returnPolicy: 'return-policy',
  userAgreement: 'user-agreement',
  personalDataNotice: 'personal-data-notice',
} as const;
