export const ADMIN_ACCESS_STATUSES = {
  ACTIVE: 'active',
  REVOKED: 'revoked',
} as const;

//===============================================================

export const ADMIN_ACCESS_ERROR_CODES = {
  ACCESS_REQUIRED: 'ADMIN_ACCESS_REQUIRED',
  ACCESS_REVOKED: 'ADMIN_ACCESS_REVOKED',
  PERMISSION_DENIED: 'ADMIN_PERMISSION_DENIED',
  PLATFORM_OWNER_REQUIRED: 'PLATFORM_OWNER_REQUIRED',
  LAST_PLATFORM_OWNER: 'LAST_PLATFORM_OWNER',
  SELF_ACCESS_CHANGE_NOT_ALLOWED: 'ADMIN_SELF_ACCESS_CHANGE_NOT_ALLOWED',
  OWNER_ACCESS_PROTECTED: 'ADMIN_OWNER_ACCESS_PROTECTED',
  PERMISSION_DELEGATION_DENIED: 'ADMIN_PERMISSION_DELEGATION_DENIED',
  INVALID_ACCESS_RECORD: 'ADMIN_INVALID_ACCESS_RECORD',
} as const;
