export const CHECKOUT_CART_CHANGED_ERROR_CODE = 'CHECKOUT_CART_CHANGED';
export const CHECKOUT_GROUP_MISSING_ERROR_CODE = 'CHECKOUT_GROUP_MISSING';
export const PHARMACY_UNAVAILABLE_ERROR_CODE = 'PHARMACY_UNAVAILABLE';

export const MANAGER_ORDER_REQUEST_REUSED_ERROR_CODE =
  'MANAGER_ORDER_REQUEST_REUSED';

export const PAYMENT_METHOD_UNAVAILABLE_ERROR_CODE =
  'PAYMENT_METHOD_UNAVAILABLE';
