export const PRODUCT_MANAGEMENT_ERROR_CODES = {
  PHARMACY_NOT_FOUND: 'PRODUCT_MANAGEMENT_PHARMACY_NOT_FOUND',
  PHARMACY_LOCKED: 'PRODUCT_MANAGEMENT_PHARMACY_LOCKED',
  PRODUCT_BLOCKED: 'PRODUCT_MANAGEMENT_PRODUCT_BLOCKED',
  ALREADY_ADDED: 'PRODUCT_MANAGEMENT_ALREADY_ADDED',
  NOT_ADDED: 'PRODUCT_MANAGEMENT_NOT_ADDED',
  HAS_RELATED_ORDERS: 'PRODUCT_MANAGEMENT_HAS_RELATED_ORDERS',
} as const;
