export const ADMIN_ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  PASSWORD_RECOVERY: '/password-recovery',
  RESET_PASSWORD: '/reset-password',
  PROFILE: '/admin/profile',
  DASHBOARD: '/admin/dashboard',
  PHARMACY_OWNERS: '/admin/pharmacy-owners',
  PHARMACIES: '/admin/pharmacies',
  PRODUCTS: '/admin/products',
  PRODUCT_REQUESTS: '/admin/product-requests',
  CLIENTS: '/admin/clients',
  ORDERS: '/admin/orders',
  REVIEWS_PHARMACIES: '/admin/reviews/pharmacies',
  REVIEWS_PRODUCTS: '/admin/reviews/products',
  SETTINGS_EMPLOYEES: '/admin/settings/employees',
  SETTINGS_POSITIONS: '/admin/settings/positions',
  SETTINGS_SITE_PAGES: '/admin/settings/site-pages',
  SETTINGS_PRODUCT_CATEGORIES: '/admin/settings/categories',
  SETTINGS_ACTIVITY: '/admin/settings/activity',
} as const;
